name: utf
version: 0.9.1-dev
author: Dart Team <misc@dartlang.org>
description: >
 A Unicode library. Intended for advanced use where the built-in facilities
 are too limiting.
homepage: https://www.github.com/dart-lang/utf
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '<0.12.0'
